export const AUTH_APP_LABELS = {
    variables: {
        sign_in: {
            email_label: "メールアドレス",
            password_label: "パスワード",
            email_input_placeholder: "メールアドレスを入力",
            password_input_placeholder: "パスワードを入力",
            button_label: "アカウント作成",
            loading_button_label: "アカウント作成中...",
            social_provider_text: "次のサービスでログイン",
            link_text: "アカウントを作成",
            confirmation_text: "アカウント作成が完了しました、メールの確認をお願いします",
        },
        sign_up: {
            email_label: "メールアドレス",
            password_label: "パスワード",
            email_input_placeholder: "メールアドレスを入力",
            password_input_placeholder: "パスワードを入力",
            button_label: "ログイン",
            loading_button_label: "ログイン中...",
            social_provider_text: "次のサービスでログイン",
            link_text: "ログインはこちら",
            confirmation_text: "ログインが完了しました",
        },
        forgotten_password: {
            email_label: "メールアドレス",
            password_label: "パスワード",
            email_input_placeholder: "メールアドレスを入力",
            button_label: "パスワードをリセット",
            loading_button_label: "パスワードをリセット中...",
            link_text: "パスワードをリセット（お忘れの場合もこちら）",
            confirmation_text: "パスワードのリセットが完了しました",
        },
    },
};